<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.23">
  <POU Name="FB_RoomController_Test_CFC" Id="{947ac3f7-77b7-4579-afcf-2cbd7219aaa2}">
    <Declaration><![CDATA[PROGRAM FB_RoomController_Test_CFC
VAR
	fbRoomController	:	FB_RoomController;
	fbLight01			:	FB_MySpecialDimmingLight;
	fbLight02			:	FB_DelayedLight;
	fbLight03			:	FB_DimmingLight;
	bAllOn				:	BOOL := FALSE;
	bAllOff				:	BOOL;
	bAllCallMinLevel	:	BOOL;
	aControlLevel		:	ARRAY [1..3] OF BOOL;
	aDimmLevel			:	ARRAY [1..3] OF BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>﻿<XmlArchive>
  <Data>
    <o xml:space="preserve" t="CFCImplementationObject">
      <o n="Items" t="CFCItemList">
        <l2 n="InnerList">
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">122L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"fbLight02"</v>
              <v n="Modifiable">true</v>
              <v n="Id">123L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"5, 8, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">121L</v>
          </o>
          <o t="CFCBoxElement">
            <o n="Inputs" t="CFCItemList">
              <l2 n="InnerList" cet="CFCInputPin">
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">20L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">22L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">69L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">161L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">163L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">165L</v>
                </o>
              </l2>
            </o>
            <o n="Outputs" t="CFCItemList">
              <l2 n="InnerList" cet="CFCOutputPin">
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">34L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Negated">false</v>
                  <v n="SetReset" t="SetReset">None</v>
                  <v n="SetResetRef" t="SetResetRef">None</v>
                  <v n="PretendsToBeConnected">false</v>
                  <v n="Id">36L</v>
                </o>
              </l2>
            </o>
            <o n="Texts" t="CFCItemList">
              <l2 n="InnerList" cet="CFCText">
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"bAllOn"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">21L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"bAllOff"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">23L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"bAllCallMinLevel"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">70L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"refLight01"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">162L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"refLight02"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">164L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"refLight03"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">166L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"aControlLevel"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">35L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"aDimmLevel"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">37L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"FB_RoomController"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">18L</v>
                </o>
                <o>
                  <v n="Bounds">"0, 0, 0, 0"</v>
                  <n n="ElementGroupId" />
                  <v n="Text">"fbRoomController"</v>
                  <v n="Modifiable">true</v>
                  <v n="Id">19L</v>
                </o>
              </l2>
            </o>
            <o n="Parameters" t="CFCItemList">
              <l2 n="InnerList" />
            </o>
            <v n="PageArea">0</v>
            <v n="Bounds">"13, 2, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="EnEno">false</v>
            <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
            <v n="OwningPageId">-1L</v>
            <v n="Id">11L</v>
          </o>
          <o t="CFCOutputElement">
            <o n="Input" t="CFCInputPinWithSetReset">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">98L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"aControlLevel"</v>
              <v n="Modifiable">true</v>
              <v n="Id">99L</v>
            </o>
            <v n="PageArea">4</v>
            <v n="Bounds">"29, 4, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">97L</v>
          </o>
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">57L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"bAllOn"</v>
              <v n="Modifiable">true</v>
              <v n="Id">58L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"6, 4, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">56L</v>
          </o>
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">54L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"bAllOff"</v>
              <v n="Modifiable">true</v>
              <v n="Id">55L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"6, 5, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">53L</v>
          </o>
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">92L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"bAllCallMinLevel"</v>
              <v n="Modifiable">true</v>
              <v n="Id">93L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"3, 6, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">91L</v>
          </o>
          <o t="CFCOutputElement">
            <o n="Input" t="CFCInputPinWithSetReset">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">101L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"aDimmLevel"</v>
              <v n="Modifiable">true</v>
              <v n="Id">102L</v>
            </o>
            <v n="PageArea">4</v>
            <v n="Bounds">"29, 5, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">100L</v>
          </o>
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">39L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"fbLight01"</v>
              <v n="Modifiable">true</v>
              <v n="Id">40L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"5, 7, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">38L</v>
          </o>
          <o t="CFCInputElement">
            <o n="Output" t="CFCOutputPin">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Negated">false</v>
              <v n="SetReset" t="SetReset">None</v>
              <v n="SetResetRef" t="SetResetRef">None</v>
              <v n="PretendsToBeConnected">false</v>
              <v n="Id">45L</v>
            </o>
            <o n="Text" t="CFCText">
              <v n="Bounds">"0, 0, 0, 0"</v>
              <n n="ElementGroupId" />
              <v n="Text">"fbLight03"</v>
              <v n="Modifiable">true</v>
              <v n="Id">46L</v>
            </o>
            <v n="PageArea">3</v>
            <v n="Bounds">"5, 9, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="OwningPageId">-1L</v>
            <v n="Id">44L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">57L</v>
            <v n="DestPinId">20L</v>
            <v n="Id">59L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">54L</v>
            <v n="DestPinId">22L</v>
            <v n="Id">60L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">92L</v>
            <v n="DestPinId">69L</v>
            <v n="Id">94L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">36L</v>
            <v n="DestPinId">101L</v>
            <v n="Id">103L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">34L</v>
            <v n="DestPinId">98L</v>
            <v n="Id">104L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">39L</v>
            <v n="DestPinId">161L</v>
            <v n="Id">176L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">45L</v>
            <v n="DestPinId">165L</v>
            <v n="Id">177L</v>
          </o>
          <o t="CFCConnection">
            <v n="Bounds">"0, 0, 0, 0"</v>
            <n n="ElementGroupId" />
            <v n="SourcePinId">122L</v>
            <v n="DestPinId">163L</v>
            <v n="Id">178L</v>
          </o>
        </l2>
      </o>
      <o n="RoutingPathTable" t="CFCRoutingPathTable">
        <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
          <o>
            <v n="ConnectionId">94L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">6</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">6</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">6</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">103L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">27</v>
              <v n="Y">5</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">27</v>
                <v n="Y">5</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">28</v>
                <v n="Y">5</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">104L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">27</v>
              <v n="Y">4</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">27</v>
                <v n="Y">4</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">28</v>
                <v n="Y">4</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">60L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">5</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">5</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">5</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">59L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">4</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">4</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">4</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">176L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">7</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">7</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">7</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">177L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">9</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">9</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">9</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
          <o>
            <v n="ConnectionId">178L</v>
            <o n="StartPoint" t="CFCPoint">
              <v n="X">11</v>
              <v n="Y">8</v>
              <v n="IsJoint">false</v>
              <v n="Flags">0</v>
            </o>
            <v n="Unroutable">false</v>
            <n n="CorrespondingPageId" />
          </o>
          <o>
            <l2 n="InnerList" cet="CFCPoint">
              <o>
                <v n="X">11</v>
                <v n="Y">8</v>
                <v n="IsJoint">false</v>
                <v n="Flags">100</v>
              </o>
              <o>
                <v n="X">12</v>
                <v n="Y">8</v>
                <v n="IsJoint">false</v>
                <v n="Flags">97</v>
              </o>
            </l2>
          </o>
        </d2>
      </o>
      <v n="AutoSizeCanvas">true</v>
      <v n="CanvasWidth">38</v>
      <v n="CanvasHeight">12</v>
    </o>
  </Data>
  <TypeList>
    <Type n="Boolean">System.Boolean</Type>
    <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
    <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
    <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
    <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
    <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
    <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
    <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
    <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
    <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
    <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
    <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
    <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
    <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
    <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
    <Type n="Int32">System.Int32</Type>
    <Type n="Int64">System.Int64</Type>
    <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
    <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
    <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
    <Type n="String">System.String</Type>
  </TypeList>
</XmlArchive></CFC>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>